### ISSUE TITLE
Any screenshots?

### ISSUE THREAD

**Issue by pahaz** [bosondata/badwolf#1]

**Comment by messense** [comment]
Here you go:

![image](https://cloud.githubusercontent.com/assets/1556054/18815932/eefff472-8370-11e6-9066-e105883618c7.png)

![image](https://cloud.githubusercontent.com/assets/1556054/18815936/000db92a-8371-11e6-9e68-84f69e6c8ebb.png)

![image](https://cloud.githubusercontent.com/assets/1556054/18815938/082ff9e2-8371-11e6-823b-3043026d0b83.png)

![image](https://cloud.githubusercontent.com/assets/1556054/18815942/10b2403e-8371-11e6-9b5c-4d8ae37cb78a.png)

![image](https://cloud.githubusercontent.com/assets/1556054/18815944/18307bfa-8371-11e6-8327-cbe82f6bc61e.png)

**Comment by messense** [comment]
Updated Slack notification lately.

![image](https://cloud.githubusercontent.com/assets/1556054/19407305/f06a5360-92d0-11e6-9065-7ea636dd491a.png)

**Comment by messense** [comment]
Also the logs is colorful now.

![image](https://cloud.githubusercontent.com/assets/1556054/19407317/433bc48e-92d1-11e6-8039-a2ee3bad3b4d.png)

**Comment by pahaz** [comment]
But what about documentation? Could you please add the screenshots to docs?
